# Użycie oficjalnego obrazu dotnet jako podstawy
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Dodanie pliku csproj
COPY ./ProjectAwans/ProjectAwans.csproj /src/ProjectAwans/

# Przywrócenie zależności
RUN dotnet restore "ProjectAwans/ProjectAwans.csproj"

# Skopiowanie reszty kodu
COPY . .

WORKDIR "/src/ProjectAwans"

# Budowanie projektu
RUN dotnet build "ProjectAwans.csproj" -c Release -o /app/build

FROM build AS publish

# Publikowanie aplikacji
RUN dotnet publish "ProjectAwans.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app

# Kopiowanie aplikacji
COPY --from=publish /app/publish .

# Punkt wejścia do aplikacji
ENTRYPOINT ["dotnet", "ProjectAwans.dll"]
